### ISSUE TITLE
Better naming of pdb_tofasta entries

### ISSUE THREAD

**Issue by sbliven** [haddocking/pdb-tools#123]
It would be useful to add an option to pdb_tofasta which sets the header to something more useful. Currently the header is always `>PDB|chain`, e.g.

```
$ pdb_fetch 4hhb|pdb_tofasta |grep '>'
>PDB|ABCD
$ pdb_fetch 4hhb|pdb_tofasta -multi|grep '>'
>PDB|A
>PDB|B
>PDB|C
>PDB|D
>PDB|A
>PDB|B
>PDB|C
>PDB|D
>PDB|A
>PDB|B
>PDB|C
>PDB|D
```

Let's set aside the inclusion of HETATM chains, which is documented but seems useless to me.

The best for me would be to have an option to replace the 'PDB' part of the header with another string. That way I can loop over a directory of pdb files and get a concatenated fasta file. Currently this has to be done using sed or similar to fix the header.

Rather than 'PDB', it seems like for pdb files with a HEADER record the default should be the PDBID if available.

**Comment by JoaoRodrigues** [comment]
Bug or improvement? :)

Reading the header might be an option, would settling for the file name be a solution for you?

**Comment by joaomcteixeira** [comment]
Note that it must be an option and default to `PDB` if the file name (for example) is not available. Remember we use `pdb-tools` as part of many pipping workflows as well as a python library. Many times we do:

```python
from pdbtools import pdb_tofasta

pdb_tofasta.run(fhandler)
```

Where handler can be a file, a list of strings or another generator. Keep this in mind when setting to report the PDB filename in the fast header, because that information might not be available.
