### ISSUE TITLE
What happened to the old `pdb_delocc` tool?

### ISSUE THREAD

**Issue by amjjbonvin** [haddocking/pdb-tools#15]
In the previous version we had the `pdb_delocc` tool that was removing double occupancies, keeping only the first instance. Did we lost it?

We have been advertising in the HADDOCK forum as a solution for double occupancies that raise an error on the server.

**Comment by mtrellet** [comment]
I mentioned it in an answer (http://ask.bioexcel.eu/t/haddock-server-problem/591/5?u=mtrellet), it has been replaced by `pdb_selaltloc.py`.

**Comment by amjjbonvin** [comment]
OK - missed that one.  We must then also check all our online tutorials since we must be advertising it at several locations

**Comment by mtrellet** [comment]
Indeed, I'll try to check my mentions to it in the forum and edit my answers when possible

**Comment by JoaoRodrigues** [comment]
I changed the names of a few tools in the new release to make them more obvious and to add some functionality. In the case of `pdb_delocc`, it became `pdb_selaltloc` to both be more obvious and also because I added the possibility of picking a specific altloc identifier. By default, it picks the one, for each atom, with the highest occupancy value.
