### ISSUE TITLE
pdb_selchain is not able to extract a chain with lowercase chain ID when the uppercase is present

### ISSUE THREAD

**Issue by DarioMarzella** [haddocking/pdb-tools#41]
**Description**
When running pdb_selchain on a PDB file containing both uppercase chain IDs and lowercase chain IDs and trying to exctract only a chain with a lowercase ID, pdb_selchain will instead extract the chain with the uppercase ID character.

**To Reproduce**
Sample pdb: 4L29.pdb
Output: 4L29_m.pdb will have only chain 'M'
```
pdb_selchain -m 4L29.pdb > 4L29_m.pdb

```

**Expected behavior**
The output file should have only chain 'm' (lowercase), not chain 'M' (uppercase).

**Desktop:**
 - OS: Mac OS
 - Python Version: 2.7

**Comment by joaomcteixeira** [comment]
Hi @DarioMarzella 
This issue was also reported in #39 and solved in #40. Though this update was not added to PyPI, which currently has version 2.0.0 (some commits behind the `master` branch).

If you want to use this functionality right away, you should reinstall pdb-tools from the `master` branch of this git repository:

`pip install git+git://github.com/haddocking/pdb-tools.git`

I will open a new issue to require update of the PyPI version.
