### ISSUE TITLE
pdb_validate.py output might not be to stderr

### ISSUE THREAD

**Issue by brianjimenez** [haddocking/pdb-tools#43]
**Describe the bug**
This is not a bug itself, but the output of the validation, when it's not correct at all, writes to stderr the result of the warnings instead of the stdout. As long as the expected output of the tool is always valid, I will expect to output to stdout and not stderr.

**To Reproduce**
```
pdb_fetch.py 2oob | pdb_validate.py
```

**Expected behavior**
Any output should be to `stdout`.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Python Version 3.7

**Comment by joaomcteixeira** [comment]
Hi @brianjimenez ,

Do you refer to all the `sys.stderr` that are in the [validation function](https://github.com/haddocking/pdb-tools/blob/b39fb96c24e00ce845417694266d7ca7a5031328/pdbtools/pdb_validate.py#L74-L160), right?

The idea you propose is that an error in the PDB file is NOT an error in the script execution itself, or the input parameters, therefore those messages should be `sys.stdout`  instead of `sys.stderr`. Is that it?

**Comment by brianjimenez** [comment]
Correct! Sorry for my poor description :)
Indeed, the result of the validation, positive or negative, should be written to `sys.stdout`.

**Comment by joaomcteixeira** [comment]
You explained well, I just wanted to double check.

PR in #44 

I don't know if this is a `bug` though, as you said in your first comment. I would rather call it an enhancement. Up to @JoaoRodrigues to decide.

**Comment by JoaoRodrigues** [comment]
If I recall correctly, the reason why I had the default output stream be `stderr` was that because if there is an output, it is a problem in the file.

But fine by me, I'd only keep the calls where there are _errors_ going to `stderr`. I'll comment in the PR.

**Comment by JoaoRodrigues** [comment]
Addressed by #44 and merged.
